# Generated by Django 3.0.11 on 2021-02-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(verbose_name='Полная ссылка')),
                ('short_url', models.CharField(max_length=200, verbose_name='Короткая ссылка')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
